### ISSUE TITLE
Add ability to add people to queue while game in progress

### ISSUE THREAD

**Issue by tormeh** [gesundkrank/mrfoosball#59]
Sometimes I hear people playing, and I think to myself that I want to play kicker. But I can't add myself to the queue for the next game, so I have to wait until after the current game is done to add myself.

**Acceptance Criteria**

- [x] Users are able to add themselves to the queue while a game is running
- [x] Rematch works as before

**Comment by ArnoFelix** [comment]
That's a great idea, having a queue that can 'backlog' players!

**Comment by gesundkrank** [comment]
I also thought about that already. The question is how it behaves in case of a rematch. 
I see two possibilities: 
1. Rematches stay as they are and it would only affect the queue after the game with all its rematches has ended.
2. Classical rematch is only possible if the queue is empty and if it's not empty the winners would play against the next players in the queue (that would be more kind of a bar approach).
@tormeh WDYT?

**Comment by tormeh** [comment]
Keeping rematch as-is is the safest choice. Although it's unfair in theory,
people rarely hog the kicker table for very long in practice, and the
interruption would be annoying, I think. I think the backlog should only
take effect once the match and all of its rematches are done.

Le ven. 1 mars 2019 à 12:09, Jan Graßegger <notifications@github.com> a
écrit :

**Comment by gesundkrank** [comment]
**Acceptance Criteria**

- [ ] Users are able to themselves to the queue while a game is running
- [ ] Rematch works as before
